---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
  labels:
    app: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart-microservice
          image: 17rj/cart-microservice
          ports:
            - containerPort: 1004


---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  selector:
    app: cart
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 1004
      targetPort: 1004
