---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoe-deployment
  namespace: webapps
  labels:
    app: shoe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoe
  template:
    metadata:
      labels:
        app: shoe
    spec:
      containers:
        - name: shoe-microservice
          image: 17rj/shoe-microservice:latest
          ports:
            - containerPort: 1002


---
apiVersion: v1
kind: Service
metadata:
  name: shoe-service
  namespace: webapps
spec:
  selector:
    app: shoe
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 1002
      targetPort: 1002
