---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  namespace: webapps
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: 17rj/ui-microservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8080
  type: LoadBalancer
