---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-deployment
  namespace: webapps
  labels:
    app: zuul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zuul
  template:
    metadata:
      labels:
        app: zuul
    spec:
      containers:
        - name: zuul
          image: 17rj/zuul-microservice:latest
          ports:
            - containerPort: 9999


---
apiVersion: v1
kind: Service
metadata:
  name: zuul-service
spec:
  selector:
    app: zuul
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
  type: LoadBalancer

